networks:
  db_segment:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.214.1
        subnet: 192.168.214.0/24
  fw_link:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.254.1
        subnet: 192.168.254.0/29
  internet:
    driver: bridge
    ipam:
      config:
      - gateway: 199.203.100.1
        subnet: 199.203.100.0/24
  mdz_segment:
    driver: bridge
    ipam:
      config:
      - gateway: 172.16.100.1
        subnet: 172.16.100.0/24
  server_segment:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.200.1
        subnet: 192.168.200.0/24
  siem_segment:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.66.1
        subnet: 192.168.66.0/24
  user_segment:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.100.1
        subnet: 192.168.100.0/24
  vpn_segment:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.110.1
        subnet: 192.168.110.0/24
services:
  attack-node:
    command:
    - sleep
    - infinity
    container_name: attack-node
    image: python:3.9-slim
    networks:
      internet:
        ipv4_address: 199.203.100.11
    tty: true
  attacker:
    command:
    - sleep
    - infinity
    container_name: attacker
    image: python:3.9-slim
    networks:
      internet:
        ipv4_address: 199.203.100.10
    tty: true
  cnt-db:
    build: ../images/cnt-db
    container_name: cnt-db
    environment:
    - POSTGRES_PASSWORD=dbpass
    - COMPANY=ACME_CORP
    - USERNAME=dbadmin
    - PASSWORD=db@admin123
    - DEPARTMENT=数据库管理
    - ROLE=数据库管理员
    - HOST_TYPE=CNT-DB
    - EMAIL=dbadmin@acmecorp.com
    - OS=CentOS 8
    - KERNEL=4.18.0-240
    networks:
      db_segment:
        ipv4_address: 192.168.214.10
    ports:
    - 5432:5432
  cnt-dmz-apache1:
    build: ../images/cnt-dmz-apache
    container_name: cnt-dmz-apache1
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=apacheadmin
    - PASSWORD=apache@admin123
    - DEPARTMENT=IT运维
    - ROLE=Web服务器管理员
    - HOST_TYPE=CNT-DMZ-APACHE
    - EMAIL=apacheadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.11
    ports:
    - 8089:80
  cnt-dmz-dns:
    build: ../images/cnt-dmz-dns
    command: "bash -c \"mkdir -p /run/named && \n        mkdir -p /usr/share/dns &&\
      \ \n        touch /usr/share/dns/root.hints && \n        chown -R bind:bind\
      \ /run/named /usr/share/dns && \n        named -g -u bind\"\n"
    container_name: cnt-dmz-dns
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=dnsadmin
    - PASSWORD=dns@admin123
    - DEPARTMENT=网络运维
    - ROLE=DNS服务器管理员
    - HOST_TYPE=CNT-DMZ-DNS
    - EMAIL=dnsadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.53
    privileged: true
    volumes:
    - /tmp/dns/run:/run/named
    - /tmp/dns/share:/usr/share/dns
  cnt-dmz-fw:
    build: ../images/fw
    container_name: cnt-dmz-fw
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=dmzfwadmin
    - PASSWORD=dmzfw@admin123
    - DEPARTMENT=网络安全
    - ROLE=DMZ防火墙管理员
    - HOST_TYPE=CNT-DMZ-FW
    - EMAIL=dmzfwadmin@acmecorp.com
    - OS=CentOS 8
    - KERNEL=4.18.0-240
    networks:
      fw_link:
        ipv4_address: 192.168.254.2
      internet:
        ipv4_address: 199.203.100.2
      mdz_segment:
        ipv4_address: 172.16.100.254
    privileged: true
  cnt-dmz-mailrelay:
    build: ../images/cnt-dmz-mailrelay
    container_name: cnt-dmz-mailrelay
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=mailadmin
    - PASSWORD=mail@admin123
    - DEPARTMENT=IT运维
    - ROLE=邮件服务器管理员
    - HOST_TYPE=CNT-DMZ-MAIL
    - EMAIL=mailadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.25
    ports:
    - '2525:25'
  cnt-dmz-wp1:
    build: ../images/cnt-dmz-wp1
    container_name: cnt-dmz-wp1
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=wpadmin
    - PASSWORD=wp@admin123
    - DEPARTMENT=市场部
    - ROLE=网站管理员
    - HOST_TYPE=CNT-DMZ-WP
    - EMAIL=wpadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.10
    ports:
    - 8087:80
  cnt-files:
    build: ../images/cnt-files
    container_name: cnt-files
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=fileadmin
    - PASSWORD=file@admin123
    - DEPARTMENT=IT运维
    - ROLE=文件服务器管理员
    - HOST_TYPE=CNT-FILES
    - EMAIL=fileadmin@acmecorp.com
    networks:
      server_segment:
        ipv4_address: 192.168.200.6
    ports:
    - 8091:80
  cnt-fw:
    build: ../images/fw
    container_name: cnt-fw
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=fwadmin
    - PASSWORD=fw@admin123
    - DEPARTMENT=网络安全
    - ROLE=防火墙管理员
    - HOST_TYPE=CNT-FW
    - EMAIL=fwadmin@acmecorp.com
    - OS=CentOS 8
    - KERNEL=4.18.0-240
    networks:
      db_segment:
        ipv4_address: 192.168.214.254
      fw_link:
        ipv4_address: 192.168.254.3
      server_segment:
        ipv4_address: 192.168.200.254
      siem_segment:
        ipv4_address: 192.168.66.254
      user_segment:
        ipv4_address: 192.168.100.254
      vpn_segment:
        ipv4_address: 192.168.110.254
    privileged: true
  cnt-sql:
    build: ../images/cnt-sql
    container_name: cnt-sql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpass
    - COMPANY=ACME_CORP
    - ROLE=server
    - HOST_TYPE=CNT-SQL
    networks:
      server_segment:
        ipv4_address: 192.168.200.23
    ports:
    - 3307:3307
  cnt-syslog:
    build: ../images/cnt-syslog
    container_name: cnt-syslog
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=syslogadmin
    - PASSWORD=syslog@admin123
    - DEPARTMENT=安全运维
    - ROLE=日志管理员
    - HOST_TYPE=CNT-SYSLOG
    - EMAIL=syslog@acmecorp.com
    networks:
      siem_segment:
        ipv4_address: 192.168.66.20
    ports:
    - 514:514/udp
  vpn:
    build: ../images/vpn
    cap_add:
    - NET_ADMIN
    command: sleep infinity
    container_name: vpn
    devices:
    - /dev/net/tun:/dev/net/tun
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=vpnadmin
    - PASSWORD=vpn@admin123
    - DEPARTMENT=网络安全
    - ROLE=VPN管理员
    - HOST_TYPE=VPN-SERVER
    - EMAIL=vpnadmin@acmecorp.com
    - OS=Ubuntu 20.04 LTS
    - KERNEL=5.4.0-42-generic
    networks:
      vpn_segment:
        ipv4_address: 192.168.110.5
    ports:
    - 1194:1194/udp
    - 7505:7505
    - 8000:8000
    privileged: true
    volumes:
    - /tmp/vpn/log:/var/log
    - /tmp/vpn/share:/opt/share
  ws-ubuntu-cnt1:
    build: ../images/ws-ubuntu
    container_name: ws-ubuntu-cnt1
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=alice
    - PASSWORD=alice123
    - ROLE=developer
    - DEPARTMENT=研发部
    - EMAIL=alice@acmecorp.com
    - POSITION=高级软件工程师
    - OS=Ubuntu 20.04 LTS
    - KERNEL=5.4.0-42-generic
    - HOST_TYPE=WS-UBUNTU
    networks:
      user_segment:
        ipv4_address: 192.168.100.9
    ports:
    - 5001:5000
  ws-ubuntu-cnt2:
    build: ../images/ws-ubuntu
    container_name: ws-ubuntu-cnt2
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=bob
    - PASSWORD=bob123
    - ROLE=qa
    - DEPARTMENT=测试部
    - EMAIL=bob@acmecorp.com
    - POSITION=测试工程师
    - OS=Ubuntu 20.04 LTS
    - KERNEL=5.4.0-42-generic
    - HOST_TYPE=WS-UBUNTU
    networks:
      user_segment:
        ipv4_address: 192.168.100.34
    ports:
    - 5002:5000
version: '3.8'
