services:
  cnt-sql:
    build: ../../images/cnt-sql
    container_name: cnt-sql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpass
    - COMPANY=ACME_CORP
    - ROLE=server
    - HOST_TYPE=CNT-SQL
    networks:
      server_segment:
        ipv4_address: 192.168.200.23
    ports:
    - 3307:3307
  cnt-files:
    build: ../../images/cnt-files
    container_name: cnt-files
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=fileadmin
    - PASSWORD=file@admin123
    - DEPARTMENT=IT运维
    - ROLE=文件服务器管理员
    - HOST_TYPE=CNT-FILES
    - EMAIL=fileadmin@acmecorp.com
    networks:
      server_segment:
        ipv4_address: 192.168.200.6
    ports:
    - 8088:80
  cnt-syslog:
    build: ../../images/cnt-syslog
    container_name: cnt-syslog
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=syslogadmin
    - PASSWORD=syslog@admin123
    - DEPARTMENT=安全运维
    - ROLE=日志管理员
    - HOST_TYPE=CNT-SYSLOG
    - EMAIL=syslog@acmecorp.com
    networks:
      siem_segment:
        ipv4_address: 192.168.66.20
    ports:
    - 514:514/udp
  ws-ubuntu-cnt1:
    build: ../../images/ws-ubuntu
    container_name: ws-ubuntu-cnt1
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=alice
    - PASSWORD=alice123
    - ROLE=developer
    - DEPARTMENT=研发部
    - EMAIL=alice@acmecorp.com
    - POSITION=高级软件工程师
    - OS=Ubuntu 20.04 LTS
    - KERNEL=5.4.0-42-generic
    - HOST_TYPE=WS-UBUNTU
    networks:
      user_segment:
        ipv4_address: 192.168.100.9
    ports:
    - 5001:5000
  ws-ubuntu-cnt2:
    build: ../../images/ws-ubuntu
    container_name: ws-ubuntu-cnt2
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=bob
    - PASSWORD=bob123
    - ROLE=qa
    - DEPARTMENT=测试部
    - EMAIL=bob@acmecorp.com
    - POSITION=测试工程师
    - OS=Ubuntu 20.04 LTS
    - KERNEL=5.4.0-42-generic
    - HOST_TYPE=WS-UBUNTU
    networks:
      user_segment:
        ipv4_address: 192.168.100.34
    ports:
    - 5002:5000
  attacker:
    image: python:3.9-slim
    container_name: attacker
    command:
    - sleep
    - infinity
    networks:
      internet:
        ipv4_address: 199.203.100.10
    tty: true
  attack-node:
    image: python:3.9-slim
    container_name: attack-node
    command:
    - sleep
    - infinity
    networks:
      internet:
        ipv4_address: 199.203.100.11
    tty: true
  cnt-dmz-wp1:
    build: ../../images/cnt-dmz-wp1
    container_name: cnt-dmz-wp1
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=wpadmin
    - PASSWORD=wp@admin123
    - DEPARTMENT=市场部
    - ROLE=网站管理员
    - HOST_TYPE=CNT-DMZ-WP
    - EMAIL=wpadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.10
    ports:
    - 8087:80
  cnt-dmz-apache1:
    build: ../../images/cnt-dmz-apache
    container_name: cnt-dmz-apache1
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=apacheadmin
    - PASSWORD=apache@admin123
    - DEPARTMENT=IT运维
    - ROLE=Web服务器管理员
    - HOST_TYPE=CNT-DMZ-APACHE
    - EMAIL=apacheadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.11
    ports:
    - 8089:80
  cnt-dmz-dns:
    build: ../../images/cnt-dmz-dns
    container_name: cnt-dmz-dns
    privileged: true
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=dnsadmin
    - PASSWORD=dns@admin123
    - DEPARTMENT=网络运维
    - ROLE=DNS服务器管理员
    - HOST_TYPE=CNT-DMZ-DNS
    - EMAIL=dnsadmin@acmecorp.com
    volumes:
    - /tmp/dns/run:/run/named
    - /tmp/dns/share:/usr/share/dns
    command: "bash -c \"mkdir -p /run/named && \n        mkdir -p /usr/share/dns &&\
      \ \n        touch /usr/share/dns/root.hints && \n        chown -R bind:bind\
      \ /run/named /usr/share/dns && \n        named -g -u bind\"\n"
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.53
  cnt-dmz-mailrelay:
    build: ../../images/cnt-dmz-mailrelay
    container_name: cnt-dmz-mailrelay
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=mailadmin
    - PASSWORD=mail@admin123
    - DEPARTMENT=IT运维
    - ROLE=邮件服务器管理员
    - HOST_TYPE=CNT-DMZ-MAIL
    - EMAIL=mailadmin@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.25
    ports:
    - '2525:25'
  cnt-db:
    build: ../../images/cnt-db
    container_name: cnt-db
    environment:
    - POSTGRES_PASSWORD=dbpass
    - COMPANY=ACME_CORP
    - USERNAME=dbadmin
    - PASSWORD=db@admin123
    - DEPARTMENT=数据库管理
    - ROLE=数据库管理员
    - HOST_TYPE=CNT-DB
    - EMAIL=dbadmin@acmecorp.com
    - OS=CentOS 8
    - KERNEL=4.18.0-240
    networks:
      db_segment:
        ipv4_address: 192.168.214.10
    ports:
    - 5432:5432
  vpn:
    build: ../../images/vpn
    container_name: vpn
    privileged: true
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=vpnadmin
    - PASSWORD=vpn@admin123
    - DEPARTMENT=网络安全
    - ROLE=VPN管理员
    - HOST_TYPE=VPN-SERVER
    - EMAIL=vpnadmin@acmecorp.com
    - OS=Ubuntu 20.04 LTS
    - KERNEL=5.4.0-42-generic
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - /tmp/vpn/log:/var/log
    - /tmp/vpn/share:/opt/share
    command: sleep infinity
    networks:
      vpn_segment:
        ipv4_address: 192.168.110.5
    ports:
    - 1194:1194/udp
    - 7505:7505
    - 8000:8000
  cnt-fw:
    build: ../../images/fw
    container_name: cnt-fw
    privileged: true
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=fwadmin
    - PASSWORD=fw@admin123
    - DEPARTMENT=网络安全
    - ROLE=防火墙管理员
    - HOST_TYPE=CNT-FW
    - EMAIL=fwadmin@acmecorp.com
    - OS=CentOS 8
    - KERNEL=4.18.0-240
    networks:
      server_segment:
        ipv4_address: 192.168.200.254
      siem_segment:
        ipv4_address: 192.168.66.254
      user_segment:
        ipv4_address: 192.168.100.254
      vpn_segment:
        ipv4_address: 192.168.110.254
      db_segment:
        ipv4_address: 192.168.214.254
      fw_link:
        ipv4_address: 192.168.254.3
  cnt-dmz-fw:
    build: ../../images/fw
    container_name: cnt-dmz-fw
    privileged: true
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=dmzfwadmin
    - PASSWORD=dmzfw@admin123
    - DEPARTMENT=网络安全
    - ROLE=DMZ防火墙管理员
    - HOST_TYPE=CNT-DMZ-FW
    - EMAIL=dmzfwadmin@acmecorp.com
    - OS=CentOS 8
    - KERNEL=4.18.0-240
    networks:
      fw_link:
        ipv4_address: 192.168.254.2
      mdz_segment:
        ipv4_address: 172.16.100.254
      internet:
        ipv4_address: 199.203.100.2
  software-update-server:
    build: ../../images/apt-targets/update-server
    container_name: software-update-server
    hostname: updates.company.local
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=updateadmin
    - PASSWORD=update123
    - DEPARTMENT=IT运维
    - ROLE=软件更新管理员
    - HOST_TYPE=UPDATE-SERVER
    - EMAIL=updates@acmecorp.com
    networks:
      server_segment:
        ipv4_address: 192.168.200.50
    ports:
    - 8090:80
    - 8443:443
    volumes:
    - update_packages:/var/updates/packages
    - update_logs:/var/updates/logs
    labels:
    - vulnerability.weak_auth=update123
    - vulnerability.directory_traversal=/packages/../config/
    - vulnerability.file_upload=unrestricted_upload
    - vulnerability.code_injection=update_script
  dev-environment:
    build: ../../images/apt-targets/dev-server
    container_name: dev-environment
    hostname: dev.company.local
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=developer
    - PASSWORD=dev123
    - DEPARTMENT=研发部
    - ROLE=开发环境管理员
    - HOST_TYPE=DEV-SERVER
    - EMAIL=dev@acmecorp.com
    - GIT_REPO=enabled
    - DEBUG_MODE=true
    networks:
      server_segment:
        ipv4_address: 192.168.200.51
    ports:
    - 8091:80
    - '8022:22'
    - 9000:9000
    volumes:
    - dev_code:/var/dev/code
    - dev_secrets:/var/dev/secrets
    labels:
    - vulnerability.weak_ssh_key=default_keys
    - vulnerability.exposed_git=.git_directory
    - vulnerability.hardcoded_secrets=config_files
    - vulnerability.debug_info_disclosure=stack_traces
  api-gateway:
    build: ../../images/apt-targets/api-gateway
    container_name: api-gateway
    hostname: api.company.local
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=apiadmin
    - PASSWORD=api@2024
    - DEPARTMENT=IT运维
    - ROLE=API网关管理员
    - HOST_TYPE=API-GATEWAY
    - EMAIL=api@acmecorp.com
    networks:
      mdz_segment:
        ipv4_address: 172.16.100.60
    ports:
    - 8092:80
    - 8444:443
    volumes:
    - api_logs:/var/api/logs
    labels:
    - vulnerability.api_key_exposure=config_files
    - vulnerability.injection_attacks=parameter_injection
    - vulnerability.auth_bypass=token_validation
  backup-server:
    build: ../../images/apt-targets/backup-server
    container_name: backup-server
    hostname: backup.company.local
    environment:
    - COMPANY=ACME_CORP
    - USERNAME=backupadmin
    - PASSWORD=backup2024
    - DEPARTMENT=IT运维
    - ROLE=备份管理员
    - HOST_TYPE=BACKUP-SERVER
    - EMAIL=backup@acmecorp.com
    - BACKUP_ENCRYPTION=disabled
    networks:
      server_segment:
        ipv4_address: 192.168.200.52
    ports:
    - 8093:80
    - 8445:445
    volumes:
    - backup_data:/var/backup/data
    - backup_logs:/var/backup/logs
    labels:
    - vulnerability.weak_smb_config=anonymous_access
    - vulnerability.unencrypted_backups=sensitive_data
    - vulnerability.exposed_credentials=backup_scripts
    - vulnerability.privilege_escalation=backup_service
  his-server:
    build: ../../images/healthcare/his
    container_name: his-server
    hostname: his.hospital.local
    environment:
    - HOSPITAL_NAME=中心医院
    - PATIENT_DB=patients_database
    - MEDICAL_RECORDS=enabled
    - BILLING_SYSTEM=enabled
    - DEPARTMENT_SYSTEM=enabled
    - USER_ROLES=doctor,nurse,admin,pharmacist,technician
    - DB_CONNECTION=postgresql://his_user:his_pass123@medical-database:5432/his_db
    - ENCRYPTION_ENABLED=false
    networks:
      server_segment:
        ipv4_address: 192.168.200.10
    ports:
    - 8090:80
    - 8443:443
    volumes:
    - his_data:/var/his/data
    - medical_records:/var/his/records
    depends_on:
    - medical-database
    labels:
    - vulnerability.sql_injection=patient_search
    - vulnerability.weak_auth=default_passwords
    - vulnerability.session_fixation=login_session
    - vulnerability.privilege_escalation=admin_panel
  pacs-server:
    build: ../../images/healthcare/pacs
    container_name: pacs-server
    hostname: pacs.hospital.local
    environment:
    - MEDICAL_IMAGES=enabled
    - DICOM_SUPPORT=enabled
    - IMAGE_STORAGE=10TB
    - BACKUP_SYSTEM=enabled
    - DICOM_PORT=11112
    - WEB_VIEWER_PORT=8091
    networks:
      server_segment:
        ipv4_address: 192.168.200.11
    ports:
    - 8091:80
    - 11112:11112
    - 8104:104
    volumes:
    - pacs_images:/var/pacs/images
    - pacs_backup:/var/pacs/backup
    - pacs_temp:/var/pacs/temp
    labels:
    - vulnerability.dicom_unauth=anonymous_access
    - vulnerability.directory_traversal=image_viewer
    - vulnerability.file_disclosure=patient_images
  lis-server:
    build: ../../images/healthcare/lis
    container_name: lis-server
    hostname: lis.hospital.local
    environment:
    - LAB_RESULTS=enabled
    - PATHOLOGY_REPORTS=enabled
    - BLOOD_BANK=enabled
    - MICROBIOLOGY=enabled
    - CHEMISTRY_LAB=enabled
    - RESULT_INTERFACE=hl7
    networks:
      server_segment:
        ipv4_address: 192.168.200.12
    ports:
    - 8092:80
    - 8502:502
    volumes:
    - lis_data:/var/lis/data
    - lis_reports:/var/lis/reports
    labels:
    - vulnerability.unauth_access=lab_results
    - vulnerability.data_exposure=patient_lab_data
    - vulnerability.hl7_injection=result_interface
  doctor-workstation-1:
    build: ../../images/healthcare/workstation
    container_name: doctor-ws-1
    hostname: doctor-ws-01.hospital.local
    environment:
    - USER_ROLE=doctor
    - DEPARTMENT=内科
    - USERNAME=dr_zhang
    - PASSWORD=Doctor123!
    - EMAIL=zhang.doctor@hospital.com
    - ACCESS_LEVEL=high
    - PATIENT_ACCESS=full
    - SYSTEM_ACCESS=his,pacs,lis
    networks:
      user_segment:
        ipv4_address: 192.168.100.20
    ports:
    - 5901:5900
    - 3389:3389
    volumes:
    - doctor_ws1_data:/home/doctor/data
    labels:
    - vulnerability.weak_password=Doctor123!
    - vulnerability.auto_login=enabled
    - vulnerability.unpatched_os=CVE-2023-1234
    - vulnerability.shared_folders=patient_data
  nurse-workstation:
    build: ../../images/healthcare/workstation
    container_name: nurse-ws-1
    hostname: nurse-ws-01.hospital.local
    environment:
    - USER_ROLE=nurse
    - DEPARTMENT=急诊科
    - USERNAME=nurse_wang
    - PASSWORD=Nurse2024
    - EMAIL=wang.nurse@hospital.com
    - ACCESS_LEVEL=medium
    - PATIENT_ACCESS=limited
    - SYSTEM_ACCESS=his,basic_pacs
    networks:
      user_segment:
        ipv4_address: 192.168.100.30
    ports:
    - 5902:5900
    - 3390:3389
    volumes:
    - nurse_ws1_data:/home/nurse/data
    labels:
    - vulnerability.weak_password=Nurse2024
    - vulnerability.usb_autorun=enabled
    - vulnerability.browser_vulns=outdated_browser
  admin-workstation:
    build: ../../images/healthcare/workstation
    container_name: admin-ws-1
    hostname: admin-ws-01.hospital.local
    environment:
    - USER_ROLE=admin
    - DEPARTMENT=IT部门
    - USERNAME=admin_chen
    - PASSWORD=admin123
    - EMAIL=chen.admin@hospital.com
    - ACCESS_LEVEL=admin
    - SYSTEM_ACCESS=all
    - DOMAIN_ADMIN=true
    networks:
      user_segment:
        ipv4_address: 192.168.100.40
    ports:
    - 5903:5900
    - 3391:3389
    volumes:
    - admin_ws1_data:/home/admin/data
    - admin_tools:/home/admin/tools
    labels:
    - vulnerability.default_password=admin123
    - vulnerability.admin_tools_exposed=management_console
    - vulnerability.credential_storage=plaintext_passwords
    - vulnerability.remote_access=unrestricted_rdp
  medical-database:
    build: ../../images/healthcare/database
    container_name: medical-db
    hostname: meddb.hospital.local
    environment:
    - DB_TYPE=postgresql
    - POSTGRES_DB=medical_db
    - POSTGRES_USER=med_admin
    - POSTGRES_PASSWORD=MedDB2024!
    - PATIENT_RECORDS=50000
    - ENCRYPTION=disabled
    - BACKUP_SCHEDULE=daily
    - COMPLIANCE=HIPAA
    networks:
      db_segment:
        ipv4_address: 192.168.214.10
    ports:
    - 5432:5432
    volumes:
    - medical_db_data:/var/lib/postgresql/data
    - medical_db_backup:/var/backup
    - medical_db_logs:/var/log/postgresql
    labels:
    - vulnerability.weak_db_password=MedDB2024!
    - vulnerability.unencrypted_data=patient_records
    - vulnerability.backup_exposure=unencrypted_backups
    - vulnerability.log_injection=sql_logs
  medical-file-server:
    build: ../../images/healthcare/file-server
    container_name: medical-files
    hostname: files.hospital.local
    environment:
    - FILE_TYPES=documents,images,reports,policies
    - STORAGE_CAPACITY=5TB
    - ACCESS_CONTROL=basic
    - AUDIT_LOGGING=disabled
    - SHARE_PERMISSIONS=permissive
    networks:
      server_segment:
        ipv4_address: 192.168.200.60
    ports:
    - 445:445
    - 2049:2049
    - '21:21'
    volumes:
    - medical_files:/var/medical/files
    - medical_documents:/var/medical/documents
    - medical_reports:/var/medical/reports
    labels:
    - vulnerability.smb_null_session=anonymous_access
    - vulnerability.ftp_anonymous=enabled
    - vulnerability.weak_file_permissions=world_readable
    - vulnerability.backup_files_exposed=.bak_files
networks:
  fw_link:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.254.0/29
        gateway: 192.168.254.1
  server_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1
  siem_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.66.0/24
        gateway: 192.168.66.1
  user_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1
  vpn_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.110.0/24
        gateway: 192.168.110.1
  db_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.214.0/24
        gateway: 192.168.214.1
  mdz_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.100.0/24
        gateway: 172.16.100.1
  internet:
    driver: bridge
    ipam:
      config:
      - subnet: 199.203.100.0/24
        gateway: 199.203.100.1
volumes:
  update_packages:
    driver: local
  update_logs:
    driver: local
  dev_code:
    driver: local
  dev_secrets:
    driver: local
  api_logs:
    driver: local
  backup_data:
    driver: local
  backup_logs:
    driver: local
  his_data:
    driver: local
  medical_records:
    driver: local
  pacs_images:
    driver: local
  pacs_backup:
    driver: local
  pacs_temp:
    driver: local
  lis_data:
    driver: local
  lis_reports:
    driver: local
  doctor_ws1_data:
    driver: local
  nurse_ws1_data:
    driver: local
  admin_ws1_data:
    driver: local
  admin_tools:
    driver: local
  medical_db_data:
    driver: local
  medical_db_backup:
    driver: local
  medical_db_logs:
    driver: local
  medical_files:
    driver: local
  medical_documents:
    driver: local
  medical_reports:
    driver: local
